### ISSUE TITLE
Option To Disable Automatic Update Checking

### ISSUE THREAD

**Issue by 0x0D15** [GrapheneOS/platform_packages_apps_Updater#74] opened 2023-01-12 07:42 UTC
Currently it is possible to disable automatic updating by disabling this app, but it seems like there is no way to disable automatic update checking at predefined 4 hours intervals without doing so. Would you consider adding the option to disable automatic update checks, leaving the user the option to queue up manual updates exclusively? 

This change should have various benefits, namely allowing for resource conservation in resource constrained scenarios. It can additionally be optionally bundled in a change that allows the user to select the update interval itself, with one option being something along the lines of "disabled". 

Thanks for considering.

**Comment by x86pup** [comment] 2023-02-18 23:21
Duplicate of https://github.com/GrapheneOS/platform_packages_apps_Updater/issues/69

**Closed as not planned by x86pup** 2023-02-18 23:21 UTC
